import { readFile, writeFile } from 'node:fs/promises';
const protocol = (await readFile(new URL('frame-protocol.js', import.meta.url), 'utf8')).replace(/^export /gm, '');
const source = await readFile(new URL('client-main.js', import.meta.url), 'utf8');
await writeFile(new URL('client.js', import.meta.url), '// Generated by build-client.mjs. Edit client-main.js/frame-protocol.js.\n' + source.replace('/* FRAME_PROTOCOL */', protocol));
